WIP: Support transaction in the docstore
google/go-cloud pull request #3500
Opened 2024-10-11 21:26 UTC by sandeepvinayak

Please use a title starting with the name of the affected package, or \"all\",
followed by a colon, followed by a short summary of the issue. Example:
`blob/gcsblob: fix typo in documentation`.

Please reference any Issue related to this Pull Request. Example: `Fixes #1`.

See
[here](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)
for tips on good Pull Request description.

2024-10-11 21:32 UTC, sandeepvinayak commented
@eliben @vangent We are trying to add the transactions support/atomic writes in the docstore and this is the high level idea of how can we support that in go-cloud. https://docs.google.com/document/d/1UVj1kmwDfrs5qm8r7X1p4fAFmsdPEeBHcvWJ8zWF1dY/edit?tab=t.0

The PR is just at a high level to support the idea. 
Let me know what you think about it and we can help to drive it further.

2025-01-16 17:27 UTC, jba requested changes

2025-01-16 17:27 UTC, jba commented on docstore/awsdynamodb/dynamo.go
> +func (c *collection) transactWrite(ctx context.Context, actions []*driver.Action, errs []error, opts *driver.RunActionsOptions) {
This function has never been tested or documented properly, so let's go carefully.

First, it needs a doc comment.

2025-01-16 17:27 UTC, jba commented on docstore/awsdynamodb/dynamo.go
>  	setErr := func(err error) {
The idea here is that if anything in this function fails, everything fails (since it's atomic). Document that here.

2025-01-16 17:27 UTC, jba commented on docstore/awsdynamodb/dynamo.go
> +			errs[w.Index] = err
You've changed the semantics here: this is no longer atomic, since if one newWriteOp fails the others still happen.

2025-01-16 17:27 UTC, jba commented on docstore/docstore.go
> +// AtomicWrites causes all following writes in the list to execute atomically.
"to execute as a single atomic operation"

(to avoid confusion with the fact that each write already happens atomically by itself)

2025-01-16 17:27 UTC, jba commented on docstore/driver/util.go
> +			if valueExistsInMaps(a.Key, writes, writesTx) {
We don't need a whole function.
```
if _, ok := writes[a.Key]; ok {
    agets[a.Key] = a
} else if _, ok :=  writesTx[a.Key]; ok {
   agets[a.Key] = a
} else ...
```

2025-01-16 17:27 UTC, jba commented on docstore/driver/util.go
> +func valueExistsInMaps(key interface{}, maps ...map[interface{}]*Action) bool {
delete

2025-01-16 17:27 UTC, jba commented on docstore/driver/util_test.go
>  		{
Please add various cases involving atomic writes, mixed with other writes and gets before, after, and concurrently.

2025-01-16 17:27 UTC, jba commented on docstore/drivertest/drivertest.go
> +	"github.com/stretchr/testify/assert"
Do not use this package or any other assertion framework.

2025-01-16 17:27 UTC, jba commented on docstore/drivertest/drivertest.go
> +}
Can you add a test where one atomic write fails, and verify that they all fail?

2025-01-16 17:27 UTC, jba commented on docstore/memdocstore/mem.go
> +	beforeGets, gets, writes, _, afterGets := driver.GroupActions(actions)
You need to implement atomic writes for this, mongo and firestore.

2025-01-16 19:28 UTC, sandeepvinayak commented on docstore/memdocstore/mem.go
> +	beforeGets, gets, writes, _, afterGets := driver.GroupActions(actions)
yes, as we discussed planned, we will be delivering it immediately after aws and driver is in. We will do the azure, gco and mongo
https://github.com/google/go-cloud/issues/3501#issuecomment-2435614003

2025-01-17 15:48 UTC, jba commented on docstore/memdocstore/mem.go
> +	beforeGets, gets, writes, _, afterGets := driver.GroupActions(actions)
OK, thanks, I forgot.

2025-01-21 18:54 UTC, sandeepvinayak commented on docstore/awsdynamodb/dynamo.go
> +			errs[w.Index] = err
Sure, let me revert it, this was to handle the cases when the write operation is non-write kind. But I believe it makes to fail here to be semantically correct.

2025-01-21 18:56 UTC, sandeepvinayak commented on docstore/awsdynamodb/dynamo.go
> +			errs[w.Index] = err
Sure, let me revert it. It was added to handle the case if the action is non-write kind which will be somebug in the code. But I got it that it's making it semantically incorrect.

2025-01-22 01:23 UTC, sandeepvinayak commented on docstore/awsdynamodb/dynamo.go
>  	<-ch
done.

2025-01-22 01:27 UTC, sandeepvinayak commented
@jba thanks for your feedback, I addressed all of the comments, please take another look

2025-01-22 18:07 UTC, jba requested changes

2025-01-22 18:07 UTC, jba commented on docstore/awsdynamodb/dynamo.go
> +// transactWrite execute the write actions in an atomic manner, either they all succeed or they all fail together.
s/execute/executes/
s/in an atomic manner/atomically/
s/,/:/

2025-01-22 18:07 UTC, jba commented on docstore/drivertest/drivertest.go
> +	cmpDiff("66", doc["s"])
You have to check the return value of cmpDiff.

2025-01-22 18:07 UTC, jba commented on docstore/drivertest/drivertest.go
> +	cmpDiff("6", doc["s"])
First, change the "6" to "66" and make sure your test fails.
It won't.
Now check the results of cmpDiff.

I recommend you use this technique all the time: first make sure the test fails, to prove that you're testing what you think. Then make it pass.

2025-01-22 21:17 UTC, sandeepvinayak commented
@jba, I addressed your latest 2 comments

2025-01-23 04:20 UTC, sandeepvinayak commented on docstore/drivertest/drivertest.go
> +	cmpDiff("6", doc["s"])
sounds good, validated that the test didn't fail and fixed it the diff check.

2025-01-23 17:33 UTC, jba approved these changes

2025-01-23 17:50 UTC, sandeepvinayak commented
@jba the codecov report is under-reporting because the conformance tests are disabled for now but I verified the tests we added are good. I will enable the 2 conformance tests added along with with the other providers in the follow up PR.

2025-01-23 17:53 UTC, merged

2025-01-23 17:53 UTC, jba commented
Thanks for the PR! Looking forward to the follow-ups.